INSERT INTO AUTHORITY (ID, ROLE) VALUES (1, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (ID, ROLE) VALUES (2, 'ROLE_USER');

INSERT INTO SAN_USER (    ID,    USERNAME,    PASSWORD,    IS_ACTIVE,    CREDIT,    EMAIL,    ACCOUNT_NON_EXPIRED) VALUES (    1,    'san',    '$2y$12$X2ooXQY2nSx.a1frHI7U6ezJG6k/126Z50dpgXmopg/qegljoDFnu',    1,    500,    'man@example.com',    1);


