INSERT INTO "AUTHORITY"(ID,NAME )VALUES (1,'ROLE_ADMIN');
INSERT INTO "AUTHORITY"(ID,name) VALUES (2,'ROLE_USER');


INSERT INTO "SAN_USER"(ID,USERNAME, PASSWORD,CREDIT) VALUES (1,'san','$2y$12$X2ooXQY2nSx.a1frHI7U6ezJG6k/126Z50dpgXmopg/qegljoDFnu',1000);
INSERT INTO "SAN_USER"(ID,USERNAME, PASSWORD,CREDIT) VALUES (2,'man','$2y$12$X2ooXQY2nSx.a1frHI7U6ezJG6k/126Z50dpgXmopg/qegljoDFnu',1000);




INSERT INTO "AUTHORITY_USERS"(AUTHORITIES_ID,USERS_ID) VALUES (1,1);
INSERT INTO "AUTHORITY_USERS"(AUTHORITIES_ID,USERS_ID) VALUES (2,2);







